from __future__ import annotations

import json

from llm_provider import LLMProvider

from .jsonutil import complete_json

# 兩份草稿都以 data/stm32mp257f-ev1/base 的實檔為格式標準;LLM 只做「依手冊
# 內容填內容」,結構與欄位語意寫死在 prompt 裡,避免各家板子長出不同 schema。

_PROFILES_SYSTEM = """\
You draft a per-SoC peripheral profile knowledge file for a pin-assignment
solver, following an existing template format exactly.

Input: the SoC's peripheral -> signals index (derived from its datasheet
pin-mux table), plus excerpt pages from the datasheet.

Reply with ONLY a JSON object of this exact shape:
{
  "soc": "<soc>",
  "board": "<board>",
  "description": "Per-instance signal profiles. default_required_signals = minimal signal set when the user names only the peripheral; optional_signals = extras in the same mode; profile_status=needs_confirmation means the solver must ask the user before auto-expanding. DRAFT generated by knowledge_extract from the datasheet - review before use.",
  "aliases": { "<USER-FACING NAME>": "<CANONICAL PREFIX>", ... },
  "dts_label_aliases": {},
  "system_policy": "<one sentence: which system functions (debug/trace/clock-out/EVENTOUT-like) are never auto-enabled unless the user names them>",
  "families": {
    "<family, lowercase, e.g. i2c/spi/uart/sdmmc/eth/can>": {
      "default": "<mode name>",
      "modes": { "<mode>": ["<SIGNAL SUFFIX>", ...], ... }
    }, ...
  },
  "peripherals": {
    "<INSTANCE, e.g. I2C1>": {
      "profile_status": "needs_confirmation",
      "mode": "<short human hint or null>",
      "default_required_signals": [],
      "optional_signals": []
    }, ...
  }
}

Rules:
- families: only for peripheral classes where instances share a suffix scheme
  (signal = <INSTANCE>_<SUFFIX>). modes list SUFFIXES only (e.g. ["SCL","SDA"]).
  Base the suffix sets on the actual signals in the index, with datasheet
  knowledge of which subset makes a minimal working mode.
- peripherals: one entry per instance in the index (skip system functions).
  profile_status is ALWAYS "needs_confirmation" in this draft.
  Leave default_required_signals/optional_signals as [] unless the family modes
  make the minimal set obvious; mode may be a short hint like "std" or null.
- aliases: map common user-facing names to index prefixes when they differ
  (e.g. "CAN" -> "FDCAN"). Empty object if none.
"""

_REQUIRE_SYSTEM = """\
You draft a boot-constraint knowledge file for a pin-assignment solver,
following an existing template format exactly.

Input: excerpt pages of the datasheet's boot/power-on-setting section, plus the
SoC's pin-mux table (pin -> mux number -> signal) restricted to boot-related
signals.

Reply with ONLY a JSON object of this exact shape:
{
  "soc": "<soc>",
  "description": "solver input: boot_pin_locked = peripherals required for booting; pin_map rows [signal, pin, mux] are fixed constants. DRAFT generated by knowledge_extract from the datasheet - boot behaviour is board-dependent, review against the actual board design before use.",
  "boot_pin_locked": {
    "policy": "fixed_pins_are_constants; reserve_peripheral_instance",
    "pin_map_columns": ["signal", "pin", "af"],
    "groups": {
      "<PERIPHERAL INSTANCE or BOOT GROUP>": {
        "role": "<短中文標題> (<why it is boot-locked, from the datasheet>)",
        "in_kernel_dt": false,
        "solver_action": "reserve_only",
        "profile_status": "needs_confirmation",
        "pin_map": [ ["<SIGNAL>", "<PIN>", <mux number>], ... ]
      }, ...
    }
  },
  "gpio_must_pins": { "action": "keep_as_gpio; remove_from_candidate_domain", "pins": [], "silicon_fixed": {} }
}

Rules:
- Only include groups the DATASHEET itself ties to booting (boot-mode strap
  pins, boot device interfaces like QSPI/SD/eMMC/NAND named in the boot
  chapter). Do not invent board-level choices.
- pin_map rows must come from the provided pin-mux table (exact signal, pin and
  mux number). If the boot text names an interface but its pins are ambiguous
  or absent from the provided table, include the group with "pin_map": [].
- Dedicated strap pins that are not in the mux table (e.g. BOOT0/PG[3:0]) go in
  a group with "pin_map": [] and the pin names listed in "role".
- Every group gets profile_status "needs_confirmation" and solver_action
  "reserve_only" in this draft.
- role format: START with a short layman-friendly Traditional-Chinese title
  (2-8 chars, e.g. 開機模式設定腳 / SD 卡開機 / SPI Flash 開機 / NAND Flash 開機 /
  Debug 主控台 / 電源管理 PMIC), then ONE half-width " (" holding the concise
  technical basis from the datasheet (original wording, English OK). The text
  BEFORE the first half-width "(" is shown verbatim to end users as a label —
  keep it plain, no register/bit names there.
"""


def draft_peripheral_profiles(
    provider: LLMProvider,
    *,
    soc: str,
    board: str,
    all_peripheral: dict,
    excerpt: str,
) -> dict:
    index = {
        "peripherals": all_peripheral["peripherals"],
        "system": all_peripheral["system"],
    }
    user = (
        f"SOC: {soc}\nBOARD: {board}\n\n"
        f"PERIPHERAL -> SIGNALS INDEX:\n{json.dumps(index, ensure_ascii=False)}\n\n"
        f"DATASHEET EXCERPTS:\n{excerpt[:30000]}"
    )
    draft = complete_json(provider, _PROFILES_SYSTEM, user, max_tokens=32768)
    draft["soc"] = soc
    draft["board"] = board
    return draft


def draft_require(
    provider: LLMProvider,
    *,
    soc: str,
    af_table: dict[str, dict[str, str]],
    boot_text: str,
) -> dict:
    # 只給 boot 相關訊號的 pinmux 子表,控制 token 又足以填 pin_map
    boot_words = ("BOOT", "QSPI", "OSPI", "SPI", "SD", "MMC", "NAND", "EMMC", "FSPI")
    sub = {
        pin: {m: s for m, s in muxes.items() if any(w in s.upper() for w in boot_words)}
        for pin, muxes in af_table.items()
    }
    sub = {pin: muxes for pin, muxes in sub.items() if muxes}
    user = (
        f"SOC: {soc}\n\n"
        f"BOOT-RELATED SUBSET OF THE PIN-MUX TABLE (pin -> mux -> signal):\n"
        f"{json.dumps(sub, ensure_ascii=False)[:40000]}\n\n"
        f"BOOT SECTION EXCERPTS:\n{boot_text[:30000]}"
    )
    draft = complete_json(provider, _REQUIRE_SYSTEM, user, max_tokens=16384)
    draft["soc"] = soc
    return draft
